services:
  valkeydb:
    image: "valkey/valkey-extension:latest"
    container_name: valkeydb
    hostname: valkeydb
    ports:
      - "6379:6379"
    networks:
      appnet:
    volumes:
      - "./valkey:/data:rw"
    restart: unless-stopped
    command: valkey-server --save 60 1 --loglevel warning
  timescale:
    image: timescale/timescaledb:latest-pg18
    container_name: pgsql18
    hostname: pgsql18
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}"
    volumes:
      - "./pgsql:/var/lib/postgresql:rw"
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      appnet:
  
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: unless-stopped
    volumes:
      - "./mqtt/config:/mosquitto/config:rw"
      - "./mqtt/data:/mosquitto/data:rw"
      - "./mqtt/logs:/mosquitto/log:rw"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      appnet:

  #mqtt_validator:
  #  build: mqtt-validator/.
  #  image: localhost/mqtt-validator:0.01
  #  container_name: mqttvalidator_01
  #  restart: unless-stopped
  #  networks:
  #    appnet:
  #  environment:
  #    RUST_BACKTRACE: 1
  #    APP_CONFIG: '{ "broker_url": "tcp://mqtt:1883","client_id": "mqtt-vld-0_01", "input_topic": "/data/raw/input", "valid_topic": "/data/validated/output", "invalid_topic": "/data/invalid/log", "validation_regex": "^\\{\\s*\"id\":\\s*\\d+\\s*,.+\\}$" }'
  #    broker_url: "tcp://mqtt:1883"
  #    client_id: "mqtt-vld-0_01" 
  #    valid_topic: "/data/validated/output"
  #    invalid_topic: "/data/invalid/log"
  #    validation_regex: "^\\{\\s*\"id\":\\s*\\d+\\s*,.+\\}$"
  #  depends_on: [ 'mqtt' ]
    
networks:
  appnet: 
