[package]
name = "mqtt_validator_service"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
paho-mqtt = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1"
dotenvy = "0.15" # Použijeme 'dotenvy', což je udržovaný fork 'dotenv'
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3.31"
